version: '3.4'

services:
  sqlserver:
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=12345
    volumes:
     - sqlserver_volume=/var/opt/mssql
    ports:
      - "1433:1433"
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"
